app:
  name: "测试案例"
  port: :8888
dataBase:
  host: 47.121.218.246
  port: 3306
  username: root
  password: 123scc
  dbname: goJob
  idleConnection: 10
  maxConnection: 100
  LiveTime: 60
jwt:
  secret: aabbccddeef
  exptime: 168
redis:
  host: 47.121.218.246
  port: 6379
  password: 123scc
  db: 0
rabbitmq:
  username: admin
  host: 47.121.218.246
  port: 5672
  password: 123scc
email:
  host: smtp.163.com
  port: 25
  username: scc_20220@163.com
  password: HQJTQUTRJRTKHIAA